#!/usr/bin/env python3
# Zuletzt geändert: 2026-08-14
# Zweck: Erzeugt shared/bus/events.schema.gen.go aus schema/events.schema.json.
# Das JSON-Schema bleibt single source of truth; die generierte Go-Datei wird
# vom Bus zur Laufzeitvalidierung eingebettet. Lauf in CI (Job "Schema-Validierung",
# Regenerierungs-Check) und lokal: python3 scripts/generate-schema.py
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "schema" / "events.schema.json"
OUT = ROOT / "shared" / "bus" / "events.schema.gen.go"

HEADER = """// Code generated by scripts/generate-schema.py; DO NOT EDIT.
package bus

// eventsSchemaJSON ist die in das Bus-Binary eingebettete Kopie von
// schema/events.schema.json (single source of truth). Bei Änderungen am
// Schema regenerieren: python3 scripts/generate-schema.py
const eventsSchemaJSON = `%s`
"""


def main() -> int:
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    raw = json.dumps(schema, indent=2, ensure_ascii=False)
    OUT.write_text(HEADER % raw, encoding="utf-8")
    print(f"{OUT} geschrieben ({len(raw)} Bytes).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
